Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2023-10, with the labels that each got.

#205 fix: hide workspace overview and settings when no workspace
  src/plugins/workspace/public/plugin.ts
Labels: all-star-contributor

#184 Add more unit test for share/delete api
  src/core/server/index.ts
  src/core/server/saved_objects/routes/integration_tests/share.test.ts
  src/core/server/saved_objects/routes/share.ts
  src/core/server/saved_objects/routes/utils.test.ts
  src/core/server/saved_objects/routes/utils.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.mock.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
Labels: seasoned-contributor

#196 [Backport workspace]Patch/first pr (#194)
  CHANGELOG.md
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  test/api_integration/apis/index.js
  test/api_integration/apis/workspace/index.ts
Labels: all-star-contributor

#206 Add integration test for workspace saved objects client wrapper
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: seasoned-contributor

#198 add permission check for bulkCreate when overwrite
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: seasoned-contributor

#215 Core module pr patch
  src/core/public/application/capabilities/capabilities_service.mock.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/index.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/capabilities/capabilities_service.mock.ts
  src/core/server/capabilities/capabilities_service.test.ts
  src/core/server/capabilities/capabilities_service.ts
  src/core/server/capabilities/integration_tests/capabilities_service.test.ts
  src/core/server/capabilities/resolve_capabilities.test.ts
  src/core/types/capabilities.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: seasoned-contributor

#207 Refactor workspace context menu register
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/index.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_header.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/core_system.test.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/plugins/plugin_context.ts
  src/core/public/plugins/plugins_service.test.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/render_workspace_menu.tsx
Labels: seasoned-contributor

#214 feat: remove unnecessary saved object get call
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: seasoned-contributor

#219 Workspace enabled flag to capabilities service
  src/core/public/application/capabilities/capabilities_service.mock.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.test.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/capabilities/capabilities_service.mock.ts
  src/core/server/capabilities/capabilities_service.test.ts
  src/core/server/capabilities/capabilities_service.ts
  src/core/server/capabilities/integration_tests/capabilities_service.test.ts
  src/core/server/capabilities/resolve_capabilities.test.ts
  src/core/types/capabilities.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/dashboard_top_nav.tsx
  src/plugins/dashboard/public/application/utils/get_nav_actions.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/visualize/public/application/utils/get_top_nav_config.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
Labels: all-star-contributor

#223 feat: add unit test for mountWrapper
  src/plugins/saved_objects_management/public/plugin.test.ts
Labels: all-star-contributor, backport workspace

#218 fix: create and bulkCreate override with target workspaces
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: seasoned-contributor

#212 [Workspace]Add workspace id in basePath
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/http/base_path.test.ts
  src/core/public/http/base_path.ts
  src/core/public/http/http_service.mock.ts
  src/core/public/http/http_service.test.ts
  src/core/public/http/http_service.ts
  src/core/public/http/types.ts
  src/core/public/index.ts
  src/core/public/utils/index.ts
  src/core/server/utils/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/__snapshots__/workspace_fatal_error.test.tsx.snap
  src/plugins/workspace/public/components/workspace_fatal_error/index.ts
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.test.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/workspace_client.mock.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor, backport workspace

#220 navigate to create workspace/workspaces list page without refreshing
  src/core/public/chrome/chrome_service.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/render_workspace_menu.tsx
Labels: all-star-contributor

#216 [API] Delete saved objects by workspace
  src/core/server/index.ts
  src/core/server/saved_objects/service/lib/repository.mock.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor, backport workspace

#210 [Workspace][Feature] Import sample data to workspace
  src/plugins/home/public/application/components/sample_data_set_cards.js
  src/plugins/home/public/application/opensearch_dashboards_services.ts
  src/plugins/home/public/application/sample_data_client.js
  src/plugins/home/public/plugin.ts
  src/plugins/home/server/services/sample_data/data_sets/ecommerce/index.ts
  src/plugins/home/server/services/sample_data/data_sets/flights/index.ts
  src/plugins/home/server/services/sample_data/data_sets/logs/index.ts
  src/plugins/home/server/services/sample_data/data_sets/util.ts
  src/plugins/home/server/services/sample_data/lib/sample_dataset_registry_types.ts
  src/plugins/home/server/services/sample_data/routes/install.test.ts
  src/plugins/home/server/services/sample_data/routes/install.ts
  src/plugins/home/server/services/sample_data/routes/list.test.ts
  src/plugins/home/server/services/sample_data/routes/list.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.test.ts
  src/plugins/home/server/services/sample_data/routes/uninstall.ts
Labels: seasoned-contributor

#227 Patch import sample data to workspace branch
  src/plugins/home/server/services/sample_data/data_sets/util.ts
Labels: all-star-contributor

#228 Support disable permission check on workspace
  config/opensearch_dashboards.yml
  src/plugins/workspace/config.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
Labels: seasoned-contributor

#225 [Backport workspace][Workspace]Add workspace id in basePath (#212)
  src/core/public/http/base_path.test.ts
  src/core/public/http/http_service.mock.ts
  src/core/public/http/http_service.test.ts
  src/core/public/index.ts
  src/core/public/utils/index.ts
  src/core/public/utils/workspace.ts
  src/core/public/workspace/index.ts
  src/core/server/utils/index.ts
  src/core/utils/index.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/__snapshots__/workspace_fatal_error.test.tsx.snap
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.test.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/public/workspace_client.mock.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor

#229 [Backport workspace]Add unit test for delete saved objects by workspace
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.test.js
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor

#231 Patch/acl
  src/core/server/saved_objects/serialization/serializer.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/types/saved_objects.ts
Labels: all-star-contributor

#226 feat: update create workspace page UI and implement unit tests
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_cancel_modal.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_icon_selector.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.ts
Labels: all-star-contributor

#192 [Workspace][Feature] Left navigation menu adjustment
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/nav_links/nav_links_service.test.ts
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/types/workspace.ts
  src/core/utils/default_app_categories.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: seasoned-contributor, backport workspace

#217 Add copy saved objects API
  src/core/server/saved_objects/routes/copy.ts
  src/core/server/saved_objects/routes/index.ts
  src/core/server/saved_objects/routes/integration_tests/copy.test.ts
Labels: valued-contributor

#235 feature: cannot delete last admin user/group in workspace settings
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
Labels: all-star-contributor

#236 Feature: create management / public workspaces when calling list api
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/console/public/application/components/import_flyout.test.tsx
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor, backport workspace

#242 Feat disable duplicate user or group permission
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor

#239 Add simple string query flags options to find method
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor

#233 [Backport workspace] Left navigation menu adjustment (#192)
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_links/nav_links_service.test.ts
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/types/workspace.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, all-star-contributor, backport workspace-pr-integr

#238 update workspace list page
  src/core/public/index.ts
  src/plugins/workspace/public/components/utils/common.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
Labels: seasoned-contributor

#245 fix: permissions missed after workspace update
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
Labels: all-star-contributor
