Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2023-08, with the labels that each got.

#69 Remove server side workspace feature flag check
  src/core/server/server.ts
  src/core/server/workspaces/workspaces_service.ts
Labels: repeat-contributor

#66 apply workspace permission check when bulk creating object
  src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: valued-contributor

#68 Register application "See more", "Home", "Create" and "Workspace Settings"
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/utils/breadcrumbs.test.ts
  src/plugins/workspace/public/components/utils/breadcrumbs.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_app.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/components/workspace_overview_app.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_updater_app.tsx
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#65 Add acl permission related functions
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/utils/constants.ts
Labels: first-time-contributor, Skip-Changelog

#73 Remove template section in workspace creation/update page
  src/core/public/application/types.ts
  src/core/public/index.ts
  src/core/types/index.ts
  src/core/types/workspace_template.ts
  src/core/utils/default_workspace_templates.ts
  src/core/utils/index.ts
  src/plugins/dashboard/public/plugin.tsx
  src/plugins/discover/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/hooks.ts
Labels: valued-contributor

#74 Integration ACL check with saved objects.
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/server/saved_objects/permission_control/client.mock.ts
  src/core/server/saved_objects/permission_control/client.ts
  src/core/server/saved_objects/permission_control/routes/principles.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/core/types/saved_objects.ts
Labels: Skip-Changelog, seasoned-contributor

#75 feat: add permission control section to workspace form
  src/core/public/index.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_client.ts
  src/core/server/workspaces/routes/index.ts
  src/core/server/workspaces/types.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
Labels: valued-contributor

#79 write permisions outside instead of workspace attributes
  src/core/public/workspace/workspaces_client.ts
  src/core/server/saved_objects/serialization/serializer.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/workspaces/index.ts
  src/core/server/workspaces/types.ts
  src/core/server/workspaces/workspaces_client.ts
Labels: seasoned-contributor

#77 Refactor UI setting register
  src/core/public/workspace/workspaces_service.ts
  src/core/server/server.ts
  src/core/server/ui_settings/settings/index.test.ts
  src/core/server/ui_settings/settings/index.ts
  src/core/server/ui_settings/settings/workspace.ts
  src/core/server/workspaces/ui_settings.ts
  src/core/server/workspaces/workspaces_service.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, repeat-contributor

#78 refactor: simplified ACL transformPermission function
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/server/saved_objects/permission_control/client.ts
  src/core/server/workspaces/routes/index.ts
Labels: Skip-Changelog, repeat-contributor

#71 Change public objects logic & Search with ACL control
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/public/utils/index.ts
  src/core/public/workspace/workspaces_client.ts
  src/core/server/saved_objects/permission_control/routes/index.ts
  src/core/server/saved_objects/permission_control/routes/principals.ts
  src/core/server/saved_objects/routes/share.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/server.ts
  src/core/server/workspaces/constants.ts
  src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/core/server/workspaces/workspaces_service.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/components/utils/workspace_column.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, seasoned-contributor

#82 Refactor workspace server plugin
  src/core/public/application/types.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/utils/index.ts
  src/core/public/workspace/consts.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/index.ts
  src/core/server/saved_objects/constants.ts
  src/core/server/saved_objects/index.ts
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/server/saved_objects/permission_control/client.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/share.ts
  src/core/server/server.ts
  src/core/server/types.ts
  src/core/server/workspaces/index.ts
  src/core/server/workspaces/ui_settings.ts
  src/core/server/workspaces/utils.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/copy_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/utils/workspace_column.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
  src/plugins/workspace/public/index.ts
  src/plugins/workspace/public/mount.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/index.ts
  src/plugins/workspace/server/saved_objects/workspace.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: valued-contributor

#76 add workspace filter into saved objects page
  src/core/public/utils/index.ts
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/lib/parse_query.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
Labels: Skip-Changelog, valued-contributor

#81 add permission check when updating workspace
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: valued-contributor

#80 feat: call saved objects with internal user
  src/plugins/workspace/server/plugin.ts
Labels: seasoned-contributor

#86 feat: workspace context menu and picker menu
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/constants.ts
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_header.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/core_system.ts
  src/core/public/utils/index.ts
  src/core/public/utils/workspace.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.ts
Labels: Skip-Changelog, valued-contributor

#89 fix: redirect to home only when delete and exit workspace successfully
  src/core/public/workspace/workspaces_service.ts
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
Labels: Skip-Changelog, valued-contributor

#92 feat: add management permission for workspace create user
  src/core/server/http/index.ts
  src/core/server/index.ts
  src/plugins/workspace/server/routes/index.ts
Labels: seasoned-contributor

#87 refactor: in left menu, move recently viewed from top to middle
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
Labels: Skip-Changelog, valued-contributor

#90 refactor: register workspace dropdown menu to left menu
  src/core/public/chrome/constants.ts
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_header.tsx
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/public/utils/index.ts
  src/core/public/utils/workspace.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/index.ts
  src/core/server/saved_objects/routes/share.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/render_workspace_menu.tsx
  src/plugins/workspace/public/types.ts
  src/plugins/workspace/public/utils.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/plugin.ts
Labels: valued-contributor

#97 fix: navigate to workspace overview after create
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
Labels: Skip-Changelog

#95 feat: accomplish dashboard_admin
  config/opensearch_dashboards.yml
  src/plugins/workspace/config.ts
  src/plugins/workspace/server/index.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: seasoned-contributor

#94 fix: two "Overview"s under library section
  src/plugins/saved_objects_management/public/constants.ts
  src/plugins/saved_objects_management/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#99 update feature config of public workspace
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/server/plugin.ts
Labels: valued-contributor

#107 fix: import error in workspace setting
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
Labels: Skip-Changelog

#62 fix: make importing workspace-specific objects as copy
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/saved_objects/import/check_conflicts.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/regenerate_ids.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/utils.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_fatal_error/index.ts
  src/plugins/workspace/public/components/workspace_fatal_error/workspace_fatal_error.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: Skip-Changelog, seasoned-contributor

#100 Change workspace id to 6 random characters
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: valued-contributor

#93 add workspace attribute check and refactor saved object acl check
  src/core/server/saved_objects/permission_control/client.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: valued-contributor

#106 filter non-configurable workspace features in workspace configuration page
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
Labels: valued-contributor

#103 feat: filter applications according to categories
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/collapsible_nav_header.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.ts
Labels: Skip-Changelog, seasoned-contributor

#102 [Refractor] Feature flag
  src/plugins/workspace/config.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
Labels: Skip-Changelog, seasoned-contributor

#111 feat: register advanced settings under Management category
  src/plugins/advanced_settings/public/management_app/components/page_wrapper/index.ts
  src/plugins/advanced_settings/public/management_app/components/page_wrapper/page_wrapper.tsx
  src/plugins/advanced_settings/public/management_app/mount_management_section.tsx
  src/plugins/advanced_settings/public/plugin.ts
Labels: Skip-Changelog, all-star-contributor

#109 fix: update snapshot for collapsible_nav.test.tsx and header.test.tsx
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
Labels: Skip-Changelog, seasoned-contributor

#115 Make index pattern always show under library
  src/plugins/data/common/index_patterns/index_patterns/index_patterns.ts
  src/plugins/data/public/index_patterns/index_patterns/redirect_no_index_pattern.tsx
  src/plugins/data/server/saved_objects/index_patterns.ts
  src/plugins/index_pattern_management/public/management_app/mount_management_section.tsx
  src/plugins/index_pattern_management/public/plugin.ts
  src/plugins/opensearch_dashboards_overview/public/components/getting_started/__snapshots__/getting_started.test.tsx.snap
  src/plugins/opensearch_dashboards_overview/public/components/getting_started/getting_started.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/relationships.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/relationships.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/workspace/public/plugin.ts
  test/api_integration/apis/saved_objects_management/find.ts
  test/api_integration/apis/saved_objects_management/relationships.ts
  test/functional/apps/management/_index_pattern_create_delete.js
Labels: Skip-Changelog, valued-contributor

#117 add workspace name duplication check
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: valued-contributor
