Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2023-06, with the labels that each got.

#21 Fix template registration import error
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/plugins/discover/public/plugin.ts
  src/plugins/visualize/public/plugin.ts
Labels: first-time-contributor

#19 Add workspace overview page
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/routes.ts
  src/plugins/workspace/public/components/workspace_overview.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog

#22 fix failed test snapshots
  .github/workflows/cypress_workflow.yml
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
Labels: first-time-contributor, Skip-Changelog

#20 change to currentWorkspace, wrap title using i18n
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
Labels: first-time-contributor, Skip-Changelog

#17 add workspace switch
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
  src/plugins/workspace/public/mount.tsx
Labels: Skip-Changelog

#25 Add update workspace page
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/routes.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_updater/index.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
Labels: first-time-contributor

#24 Delete Workspace
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/index.ts
  src/plugins/workspace/public/components/workspace_overview.tsx
Labels: first-time-contributor, Skip-Changelog

#26 Redirect to overview after workspace switch
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
Labels: repeat-contributor

#28 update menu filter logic
  src/core/public/chrome/ui/header/collapsible_nav.tsx
Labels: Skip-Changelog

#29 feat: redirect to workspace overview page after created success
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
Labels: repeat-contributor

#18 [Feature] Complied saved_objects create/find
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/create.ts
  src/core/server/saved_objects/routes/export.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/utils.ts
  src/core/server/saved_objects/serialization/serializer.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog

#27 Move delete button to update page
  src/plugins/workspace/public/components/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.ts
Labels: first-time-contributor, Skip-Changelog

#34 remove duplicate EuiPage
  src/plugins/workspace/public/components/workspace_app.tsx
  src/plugins/workspace/public/hooks.ts
Labels: Skip-Changelog, repeat-contributor

#33 remove clear button, add the width of create button
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
Labels: first-time-contributor

#32 Add some logic check when overwrite a saved object
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/types/saved_objects.ts
Labels: Skip-Changelog, valued-contributor
