Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2023-07, with the labels that each got.

#36 Add color, icon and defaultVISTheme for workspace
  src/core/server/workspaces/routes/index.ts
  src/core/server/workspaces/saved_objects/workspace.ts
  src/core/server/workspaces/types.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_icon_selector.tsx
Labels: Skip-Changelog, valued-contributor

#39 add workspace list
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/routes.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
Labels: repeat-contributor

#37 Feature/menu change
  src/core/utils/default_app_categories.ts
  src/plugins/saved_objects_management/public/constants.ts
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#38 feat: different left menu and exit workspace
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/constants.ts
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/plugins/workspace/public/components/workspace_app.tsx
  src/plugins/workspace/public/plugin.ts
Labels: first-time-contributor, Skip-Changelog

#35 feat: make url stateful
  src/core/public/fatal_errors/fatal_errors_service.mock.ts
  src/core/public/http/base_path.ts
  src/core/public/http/http_service.ts
  src/core/public/http/types.ts
  src/core/public/index.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/core/public/utils/index.ts
  src/core/public/utils/workspace.ts
  src/core/public/workspace/consts.ts
  src/core/public/workspace/index.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/workspaces/workspaces_service.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#42 Fix build error and part of test error
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/injected_metadata/injected_metadata_service.mock.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.test.ts
  src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
  src/plugins/dashboard/public/application/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
Labels: repeat-contributor

#40 feat: optimize code for stateful url
  src/core/public/http/base_path.ts
  src/core/public/http/http_service.ts
  src/core/public/http/types.ts
  src/core/public/injected_metadata/injected_metadata_service.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#41 feat: add workspace permission control interface
  src/core/server/workspaces/index.ts
  src/core/server/workspaces/workspace_permission_control.ts
  src/core/server/workspaces/workspaces_service.ts
Labels: Skip-Changelog, valued-contributor

#46 allow user to turn on/off workspace from advance settings
  src/core/public/chrome/chrome_service.tsx
  src/core/public/core_app/core_app.ts
  src/core/public/core_system.ts
  src/core/public/http/types.ts
  src/core/public/ui_settings/ui_settings_service.mock.ts
  src/core/public/workspace/workspaces_client.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/server/server.ts
  src/core/server/ui_settings/settings/index.test.ts
  src/core/server/ui_settings/settings/index.ts
  src/core/server/ui_settings/settings/workspace.ts
  src/core/server/workspaces/workspaces_service.ts
  src/plugins/workspace/public/containers/workspace_dropdown_list/workspace_dropdown_list.tsx
  src/plugins/workspace/public/mount.tsx
  src/plugins/workspace/public/plugin.ts
Labels: first-time-contributor, Skip-Changelog

#50 fix: unit test failure
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/saved_objects/saved_objects_client.test.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/utils/default_app_categories.ts
  src/plugins/dashboard/public/application/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
Labels: Skip-Changelog, valued-contributor

#44 Add workspace column into saved objects table
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/utils/workspace_column.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, repeat-contributor

#31 Integrate workspace service into saved object management
  src/core/public/chrome/chrome_service.test.ts
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header_logo.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/fatal_errors/fatal_errors_service.mock.ts
  src/core/public/mocks.ts
  src/core/public/plugins/plugins_service.test.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/server/index.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/utils.ts
  src/core/server/workspaces/index.ts
  src/core/server/workspaces/utils.ts
  src/plugins/saved_objects_management/public/lib/fetch_export_by_type_and_search.ts
  src/plugins/saved_objects_management/public/lib/fetch_export_objects.ts
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/lib/import_file.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_mode_control.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
Labels: Skip-Changelog, valued-contributor

#45 Feature: hide workspace from saved objects management page.
  src/core/public/http/base_path.ts
  src/core/public/http/http_service.ts
  src/core/public/http/types.ts
  src/core/public/index.ts
  src/core/public/utils/index.ts
  src/core/public/utils/workspace.ts
  src/core/server/index.ts
  src/core/server/workspaces/constants.ts
  src/core/server/workspaces/index.ts
  src/core/server/workspaces/saved_objects/workspace.ts
  src/core/server/workspaces/workspaces_client.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/management_section/mount_section.tsx
  src/plugins/workspace/public/components/utils/workspace_column.tsx
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor

#53 Add copy saved objects among workspaces functionality
  src/core/server/saved_objects/routes/copy.ts
  src/core/server/saved_objects/routes/index.ts
  src/plugins/saved_objects_management/public/constants.ts
  src/plugins/saved_objects_management/public/lib/copy_saved_objects.ts
  src/plugins/saved_objects_management/public/lib/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/copy_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
Labels: first-time-contributor

#51 add workspace saved objects client wrapper
  src/core/public/workspace/workspaces_client.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/workspaces/saved_objects/index.ts
  src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/core/server/workspaces/workspace_permission_control.ts
  src/core/server/workspaces/workspaces_service.ts
Labels: valued-contributor

#55 Refactor navigation links from left menu hard code to workspace plugin register
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/constants.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/header.test.tsx
  src/core/public/chrome/ui/header/header.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/core_system.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, repeat-contributor

#57 fix: osd bootstrap error
  src/core/public/core_system.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
Labels: repeat-contributor

#49 feat: filter out ADMIN application and add feature dependency logic
  src/core/public/application/types.ts
  src/plugins/workspace/public/components/utils/feature.test.ts
  src/plugins/workspace/public/components/utils/feature.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
Labels: valued-contributor

#56 feat: do not register app when feature flag is off
  src/core/utils/default_app_categories.ts
  src/plugins/saved_objects_management/public/plugin.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, seasoned-contributor

#60 Sort category and non-category nav link according to order in left menu
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, repeat-contributor

#64 Refactor: Assign default value for filtered nav links
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/plugins/workspace/public/plugin.ts
Labels: Skip-Changelog, valued-contributor

#63 Permission control service for saved objects
  src/core/server/legacy/legacy_service.ts
  src/core/server/plugins/plugin_context.ts
  src/core/server/saved_objects/permission_control/client.mock.ts
  src/core/server/saved_objects/permission_control/client.ts
  src/core/server/saved_objects/permission_control/routes/index.ts
  src/core/server/saved_objects/permission_control/routes/principles.ts
  src/core/server/saved_objects/permission_control/routes/validate.ts
  src/core/server/saved_objects/saved_objects_service.mock.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/workspaces/index.ts
  src/core/server/workspaces/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/core/server/workspaces/workspace_permission_control.ts
  src/core/server/workspaces/workspaces_service.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
Labels: Skip-Changelog, seasoned-contributor
