Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2024-03, with the labels that each got.

#261 feat: consume current workspace in saved objects management and saved objects client
  src/core/public/saved_objects/saved_objects_client.test.ts
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/public/saved_objects/saved_objects_service.mock.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.test.ts
  src/core/server/saved_objects/export/get_sorted_objects_for_export.ts
  src/core/server/saved_objects/import/resolve_import_errors.test.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/saved_objects_management/public/lib/fetch_export_by_type_and_search.ts
  src/plugins/saved_objects_management/public/lib/fetch_export_objects.test.ts
  src/plugins/saved_objects_management/public/lib/fetch_export_objects.ts
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/lib/import_file.test.ts
  src/plugins/saved_objects_management/public/lib/import_file.ts
  src/plugins/saved_objects_management/public/lib/resolve_import_errors.test.ts
  src/plugins/saved_objects_management/public/lib/resolve_import_errors.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/flyout.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/import_mode_control.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
Labels: distinguished-contributor

#271 remove personal workspace
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor

#274 feat: cherry-pick pr #5949
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/resolve_import_errors.ts
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/core/server/saved_objects/routes/import.ts
  src/core/server/saved_objects/routes/resolve_import_errors.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: distinguished-contributor

#275 feat: backport pr 5949 to workspace-pr-inte
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/import/types.ts
  src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/core/server/saved_objects/routes/bulk_create.ts
  src/core/server/saved_objects/routes/find.ts
  src/core/server/saved_objects/saved_objects_service.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: distinguished-contributor

#276 [Workspace]Following pr for #5949 (#6012)
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: distinguished-contributor

#277 [Workspace]Following pr for #5949 (#6012)
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/migration_context.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: distinguished-contributor

#259 update workspace list
  src/core/public/index.ts
  src/core/public/utils/debounce.test.ts
  src/core/public/utils/debounce.ts
  src/core/public/utils/index.ts
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/components/utils/common.ts
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_list/workspace_actions_menu.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
Labels: seasoned-contributor

#280 feat: remove useless code
  src/core/server/saved_objects/service/lib/integration_tests/repository.test.ts
Labels: distinguished-contributor

#278 remove management workspace
  src/core/public/index.ts
  src/core/public/utils/index.ts
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: first-time-contributor

#230 add permission control service for saved objects and workspace saved objects client wrapper
  config/opensearch_dashboards.yml
  src/core/public/index.ts
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/index.ts
  src/core/server/saved_objects/index.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/config.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/permission_control/client.mock.ts
  src/plugins/workspace/server/permission_control/client.test.ts
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: seasoned-contributor

#282 Add a workspace dropdown menu in left navigation bar
  src/core/public/index.ts
  src/core/public/mocks.ts
  src/core/public/utils/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/render_workspace_menu.tsx
Labels: all-star-contributor

#281 remove management workspace (#278)
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: first-time-contributor

#287 [Workspace][Feature] Backport the change of ACL in OSD-core repo to the integration branch
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/server/saved_objects/permission_control/index.ts
  src/core/server/saved_objects/saved_objects_config.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/types/saved_objects.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
Labels: valued-contributor

#286 Workspace left nav bar
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_links/index.ts
  src/core/public/chrome/nav_links/nav_link.ts
  src/core/public/chrome/nav_links/nav_links_service.test.ts
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/chrome/ui/header/collapsible_nav.test.tsx
  src/core/public/chrome/ui/header/collapsible_nav.tsx
  src/core/public/chrome/ui/header/nav_link.tsx
  src/core/public/index.ts
  src/core/public/workspace/workspaces_service.mock.ts
  src/core/public/workspace/workspaces_service.ts
  src/core/utils/default_app_categories.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dev_tools/public/plugin.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.ts
Labels: all-star-contributor

#211 Add workspace filter/column into saved objects page
  src/core/public/index.ts
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/lib/get_saved_object_counts.ts
  src/plugins/saved_objects_management/public/lib/parse_query.test.ts
  src/plugins/saved_objects_management/public/lib/parse_query.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/server/routes/find.ts
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/components/workspace_column/index.ts
  src/plugins/workspace/public/components/workspace_column/workspace_colum.test.tsx
  src/plugins/workspace/public/components/workspace_column/workspace_column.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: seasoned-contributor

#279 [Workspace][Feature] Backport the change of ACL in main
  CHANGELOG.md
  config/opensearch_dashboards.yml
  src/core/server/saved_objects/migrations/core/__snapshots__/build_active_mappings.test.ts.snap
  src/core/server/saved_objects/migrations/core/build_active_mappings.test.ts
  src/core/server/saved_objects/migrations/core/build_active_mappings.ts
  src/core/server/saved_objects/migrations/core/index_migrator.test.ts
  src/core/server/saved_objects/migrations/opensearch_dashboards/__snapshots__/opensearch_dashboards_migrator.test.ts.snap
  src/core/server/saved_objects/migrations/opensearch_dashboards/opensearch_dashboards_migrator.test.ts
  src/core/server/saved_objects/permission_control/acl.test.ts
  src/core/server/saved_objects/permission_control/acl.ts
  src/core/server/saved_objects/permission_control/index.ts
  src/core/server/saved_objects/saved_objects_config.ts
  src/core/server/saved_objects/saved_objects_service.test.ts
  src/core/server/saved_objects/serialization/types.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/saved_objects_client.ts
  src/core/types/saved_objects.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
Labels: valued-contributor

#290 [Backport workspace-pr-integr][Workspace] Consume workspace id in saved object client (#6014)
  src/core/public/saved_objects/saved_objects_client.ts
Labels: distinguished-contributor

#285 Workspace list pr
  src/core/public/index.ts
  src/core/public/utils/debounce.test.ts
  src/core/public/utils/debounce.ts
  src/core/public/utils/index.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/__snapshots__/delete_workspace_modal.test.tsx.snap
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.test.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
  src/plugins/workspace/public/components/delete_workspace_modal/index.ts
  src/plugins/workspace/public/components/utils/workspace.test.ts
  src/plugins/workspace/public/components/utils/workspace.ts
  src/plugins/workspace/public/components/workspace_list/__snapshots__/index.test.tsx.snap
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: seasoned-contributor

#296 fix: authInfo destructure (#7)
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: distinguished-contributor

#284 Add workspace create page
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_creator/index.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_cancel_modal.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_icon_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/hooks.ts
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: all-star-contributor

#299 fix failed modal cross component tests in ci env
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.test.tsx
  src/plugins/workspace/public/components/workspace_list/index.test.tsx
Labels: seasoned-contributor

#295 [Backport workspace-pr-integr] Add workspace id in base path
  src/core/public/chrome/ui/header/__snapshots__/collapsible_nav.test.tsx.snap
  src/core/public/chrome/ui/header/__snapshots__/header.test.tsx.snap
  src/core/public/http/base_path.test.ts
  src/core/public/http/base_path.ts
  src/core/public/http/http_service.mock.ts
  src/core/public/http/http_service.ts
  src/core/public/http/types.ts
  src/core/utils/workspace.test.ts
  src/core/utils/workspace.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
  src/plugins/dashboard/public/application/embeddable/empty/__snapshots__/dashboard_empty_screen.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/flyout.test.tsx.snap
  src/plugins/telemetry_management_section/public/components/__snapshots__/telemetry_management_section.test.tsx.snap
  src/plugins/workspace/public/components/delete_workspace_modal/delete_workspace_modal.tsx
Labels: distinguished-contributor

#302 [Backport workspace-pr-integr]Add support for dynamic application configurations (#5855)
  config/opensearch_dashboards.yml
  src/core/server/mocks.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/legacy/server/config/schema.js
  src/plugins/application_config/README.md
  src/plugins/application_config/common/index.ts
  src/plugins/application_config/config.ts
  src/plugins/application_config/opensearch_dashboards.json
  src/plugins/application_config/server/index.ts
  src/plugins/application_config/server/opensearch_config_client.test.ts
  src/plugins/application_config/server/opensearch_config_client.ts
  src/plugins/application_config/server/plugin.test.ts
  src/plugins/application_config/server/plugin.ts
  src/plugins/application_config/server/routes/index.test.ts
  src/plugins/application_config/server/routes/index.ts
  src/plugins/application_config/server/string_utils.test.ts
  src/plugins/application_config/server/string_utils.ts
  src/plugins/application_config/server/types.ts
Labels: distinguished-contributor

#304 Add update workspace page
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_bottom_bar.tsx
  src/plugins/workspace/public/components/workspace_updater/index.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_updater_app.tsx
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: valued-contributor

#308 [Backport workspace-pr-integr][Workspace] Add a workspace client in workspace plugin (#6094)
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
Labels: distinguished-contributor

#310 feat: remove useless code
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
Labels: distinguished-contributor

#311 feat: remove useless code
  src/core/server/saved_objects/import/import_saved_objects.test.ts
  src/core/server/saved_objects/import/import_saved_objects.ts
  src/core/server/saved_objects/import/regenerate_ids.test.ts
  src/core/server/saved_objects/import/regenerate_ids.ts
Labels: distinguished-contributor
