Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2024-04, with the labels that each got.

#309 Add features quantity in workspace list page
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/hooks.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: seasoned-contributor

#317 Workspace overview blank
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_overview/workspace_overview.tsx
  src/plugins/workspace/public/components/workspace_overview_app.tsx
  src/plugins/workspace/public/plugin.ts
Labels: seasoned-contributor

#314 Backport permission control to pr integr
  src/core/server/index.ts
  src/core/server/mocks.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/core/server/saved_objects/index.ts
  src/core/server/saved_objects/service/lib/repository.test.js
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/types/saved_objects.ts
  src/core/types/workspace.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/hooks.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/permission_control/client.test.ts
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor

#318 fix: unit test
  src/plugins/workspace/public/plugin.test.ts
Labels: distinguished-contributor

#321 Fix group permissions convert
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
Labels: all-star-contributor

#323 [Workspace] Filter left nav menu items according to the current workspace (#6234)
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: distinguished-contributor

#324 [backport]Improve dynamic configurations by adding cache and simplifying client fetch
  src/plugins/application_config/server/opensearch_config_client.test.ts
  src/plugins/application_config/server/opensearch_config_client.ts
  src/plugins/application_config/server/plugin.test.ts
  src/plugins/application_config/server/plugin.ts
  src/plugins/application_config/server/types.ts
Labels: first-time-contributor

#322 replace default workspace with public workspace
  src/core/public/index.ts
  src/core/server/index.ts
  src/core/utils/constants.ts
  src/core/utils/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/server/routes/scroll_count.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor

#326 [Backport] Add duplicate saved objects API (#6288)
  src/core/server/saved_objects/routes/index.ts
  src/plugins/saved_objects/README.md
  src/plugins/workspace/README.md
  src/plugins/workspace/server/integration_tests/duplicate.test.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/routes/duplicate.ts
  src/plugins/workspace/server/routes/index.ts
Labels: valued-contributor

#303 dashboard admin(groups/users) implementation and integrating with dynamic application config
  config/opensearch_dashboards.yml
  src/core/server/mocks.ts
  src/core/server/opensearch_dashboards_config.ts
  src/core/server/plugins/plugin_context.test.ts
  src/core/server/plugins/types.ts
  src/core/server/utils/workspace.test.ts
  src/core/server/utils/workspace.ts
  src/legacy/server/config/schema.js
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/utils.test.ts
  src/plugins/workspace/server/utils.ts
Labels: first-time-contributor

#316 [Workspace] Jump to non-workspace url when clicking home icon
  src/core/public/application/application_service.test.ts
  src/core/public/application/application_service.tsx
  src/core/public/application/index.ts
  src/core/public/application/integration_tests/application_service.test.tsx
  src/core/public/application/types.ts
  src/core/public/chrome/chrome_service.tsx
  src/core/public/chrome/nav_links/to_nav_link.test.ts
  src/core/public/chrome/nav_links/to_nav_link.ts
  src/core/public/core_system.ts
  src/core/public/index.ts
  src/plugins/home/public/plugin.ts
  src/plugins/opensearch_dashboards_overview/public/plugin.ts
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.test.tsx
  src/plugins/workspace/public/components/workspace_menu/workspace_menu.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: distinguished-contributor

#325 hide datasource and settings menu when workspace enabled and entering workspace
  src/plugins/workspace/opensearch_dashboards.json
  src/plugins/workspace/public/plugin.test.ts
  src/plugins/workspace/public/plugin.ts
Labels: seasoned-contributor

#327 [Backport workspace-pr-integr][Workspace] Support workspace in saved objects client in server side (#6365)
  src/core/server/saved_objects/import/create_saved_objects.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_id_consumer_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: distinguished-contributor

#306 Add enabledOperators parameter for workspace name unique check
  src/core/public/saved_objects/saved_objects_client.ts
  src/core/server/saved_objects/service/lib/repository.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.test.ts
  src/core/server/saved_objects/service/lib/search_dsl/query_params.ts
  src/core/server/saved_objects/service/lib/search_dsl/search_dsl.ts
  src/core/server/saved_objects/types.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: seasoned-contributor

#305 feat: duplicate selected/all saved objects UI
  src/plugins/saved_objects_management/public/index.ts
  src/plugins/saved_objects_management/public/lib/duplicate_saved_objects.test.ts
  src/plugins/saved_objects_management/public/lib/duplicate_saved_objects.ts
  src/plugins/saved_objects_management/public/lib/index.ts
  src/plugins/saved_objects_management/public/management_section/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/__snapshots__/saved_objects_table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_modal.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/duplicate_object_categories.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/header.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/__snapshots__/table.test.tsx.snap
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_modal.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_object_categories.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/duplicate_object_categories.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/header.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/table.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/utils.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/components/utils.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/index.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.mocks.ts
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.test.tsx
  src/plugins/saved_objects_management/public/management_section/objects_table/saved_objects_table.tsx
  src/plugins/saved_objects_management/public/management_section/saved_objects_table_page.tsx
  src/plugins/saved_objects_management/public/management_section/types.ts
  src/plugins/workspace/public/workspace_client.test.ts
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
  src/plugins/workspace/server/types.ts
Labels: first-time-contributor

#328 feat: workspace level ui settings
  src/core/types/workspace.ts
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/server/plugin.test.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_ui_settings_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.test.ts
  src/plugins/workspace/server/saved_objects/workspace_ui_settings_client_wrapper.ts
Labels: all-star-contributor

#331 remove unnecessary changes due to the refactor in #6234
  src/core/public/chrome/chrome_service.mock.ts
  src/core/public/chrome/index.ts
  src/core/public/chrome/nav_links/index.ts
  src/core/public/chrome/nav_links/nav_links_service.ts
  src/core/public/index.ts
  src/plugins/dashboard/public/application/components/dashboard_listing/__snapshots__/dashboard_listing.test.tsx.snap
  src/plugins/dashboard/public/application/components/dashboard_top_nav/__snapshots__/dashboard_top_nav.test.tsx.snap
Labels: all-star-contributor

#333 Manual backport workspace permission tab
  src/plugins/workspace/common/constants.ts
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_form/constants.ts
  src/plugins/workspace/public/components/workspace_form/index.ts
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/use_workspace_form.ts
  src/plugins/workspace/public/components/workspace_form/utils.test.ts
  src/plugins/workspace/public/components/workspace_form/utils.ts
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_input.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_permission_setting_panel.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/workspace_client.ts
  src/plugins/workspace/server/integration_tests/routes.test.ts
  src/plugins/workspace/server/routes/index.ts
  src/plugins/workspace/server/types.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: all-star-contributor

#313 Handle data sources and advanced settings as global object.
  src/plugins/workspace/server/saved_objects/integration_tests/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.test.ts
  src/plugins/workspace/server/saved_objects/saved_objects_wrapper_for_check_workspace_conflict.ts
Labels: distinguished-contributor

#332 Backport/backport 6459 to workspace pr integr
  src/plugins/workspace/public/application.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.test.tsx
  src/plugins/workspace/public/components/workspace_creator/workspace_creator.tsx
  src/plugins/workspace/public/components/workspace_creator_app.tsx
  src/plugins/workspace/public/components/workspace_form/types.ts
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.test.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_feature_selector.tsx
  src/plugins/workspace/public/components/workspace_form/workspace_form.tsx
  src/plugins/workspace/public/components/workspace_list/index.tsx
  src/plugins/workspace/public/components/workspace_list_app.tsx
  src/plugins/workspace/public/components/workspace_updater/index.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.test.tsx
  src/plugins/workspace/public/components/workspace_updater/workspace_updater.tsx
  src/plugins/workspace/public/components/workspace_updater_app.tsx
  src/plugins/workspace/public/plugin.ts
  src/plugins/workspace/public/utils.test.ts
  src/plugins/workspace/public/utils.ts
Labels: all-star-contributor
