Repository ruanyl/OpenSearch-Dashboards, pull requests merged in 2024-02, with the labels that each got.

#250 fix: remove duplicated reserved field avoid type error
  src/core/types/workspace.ts
Labels: all-star-contributor

#249 feat: add workspace into includeHiddenTypes
  src/plugins/workspace/server/permission_control/client.ts
  src/plugins/workspace/server/plugin.ts
  src/plugins/workspace/server/saved_objects/workspace_saved_objects_client_wrapper.ts
Labels: Skip-Changelog, all-star-contributor

#252 fix: cypress tests checkout workspace branch
  .github/workflows/cypress_workflow.yml
Labels: backport workspace

#251 fix: workspace routes integration failed
  src/plugins/workspace/server/integration_tests/routes.test.ts
Labels: all-star-contributor, backport workspace

#258 feat: remove useless code
  src/plugins/discover_legacy/public/application/components/top_nav/__snapshots__/open_search_panel.test.js.snap
  src/plugins/discover_legacy/public/application/components/top_nav/open_search_panel.js
Labels: all-star-contributor

#255 manual backport #251
  src/plugins/workspace/server/integration_tests/routes.test.ts
Labels: all-star-contributor

#260 Fix existing failed integration test cases
  src/plugins/workspace/server/saved_objects/integration_tests/workspace_saved_objects_client_wrapper.test.ts
  src/plugins/workspace/server/workspace_client.ts
Labels: distinguished-contributor
